--------------------------------------------------------
-- Archivo creado  - martes-octubre-08-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AGENCIA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."AGENCIA" 
   (	"ID_AGENCIA" NUMBER(*,0), 
	"DIRECCION" VARCHAR2(150 CHAR), 
	"DESCRIPCION" VARCHAR2(200 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BANCO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BANCO" 
   (	"ID_BANCO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(150 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHEQUE_EXTERNO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CHEQUE_EXTERNO" 
   (	"CODIGO_CHEQUE" NUMBER(*,0), 
	"FECHA" DATE, 
	"MONTO" FLOAT(126), 
	"BANCO" NUMBER(*,0), 
	"LOTE" NUMBER(*,0), 
	"ESTADO_CHEQUE" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHEQUE_LOCAL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CHEQUE_LOCAL" 
   (	"CODIGO_CHEQUE" NUMBER(*,0), 
	"FECHA" DATE, 
	"MONTO" FLOAT(126), 
	"CHEQUERA" NUMBER(*,0), 
	"ESTADO_CHEQUE" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHEQUERA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CHEQUERA" 
   (	"CODIGO_CHEQUERA" NUMBER(*,0), 
	"CANTIDAD_CHEQUES" NUMBER(*,0), 
	"CUENTA" NUMBER(*,0), 
	"NUMERO_INICIO" NUMBER(*,0), 
	"NUMERO_FINAL" NUMBER(*,0), 
	"ESTADO_CHEQUERA" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CLIENTE" 
   (	"CODIGO_CLIENTE" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(150 CHAR), 
	"DIRECCION" VARCHAR2(150 CHAR), 
	"NIT" NUMBER(*,0), 
	"TELEFONO" NUMBER(*,0), 
	"CORREO" VARCHAR2(25 CHAR), 
	"TIPO_CLIENTE" NUMBER(*,0), 
	"FOTO" BLOB, 
	"FIRMA" BLOB, 
	"DPI" VARCHAR2(20 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("FOTO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("FIRMA") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CLIENTE_CUENTA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CLIENTE_CUENTA" 
   (	"CLIENTE" NUMBER(*,0), 
	"CUENTA" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUENTA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CUENTA" 
   (	"NUMERO_CUENTA" NUMBER(*,0), 
	"ESTADO" VARCHAR2(100 CHAR), 
	"SALDO_DISPONIBLE" FLOAT(126), 
	"ESTADO_CUENTA" NUMBER(*,0), 
	"EN_RESERVA" FLOAT(126), 
	"TIPO_CUENTA" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLEADO" 
   (	"CODIGO_EMPLEADO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(150 BYTE), 
	"DIRECCION" VARCHAR2(150 BYTE), 
	"TELEFONO" NUMBER(*,0), 
	"CORREO" VARCHAR2(50 BYTE), 
	"ROL" NUMBER(*,0), 
	"AGENCIA" NUMBER(*,0), 
	"DPI" VARCHAR2(20 CHAR), 
	"CONTRASENA" VARCHAR2(10 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EQUIPO" 
   (	"SKU" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(250 CHAR), 
	"AGENCIA_ID_AGENCIA" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ESTADO_CHEQUE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ESTADO_CHEQUE" 
   (	"CODIGO" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(250 BYTE), 
	"NOMBRE" VARCHAR2(100 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ESTADO_CHEQUERA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ESTADO_CHEQUERA" 
   (	"CODIGO_ESTADO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 CHAR), 
	"DESCRIPCION" VARCHAR2(200 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ESTADO_CUENTA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ESTADO_CUENTA" 
   (	"CODIGO_ESTADO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 CHAR), 
	"DESCRIPCION" VARCHAR2(250 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ESTADO_LOTE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ESTADO_LOTE" 
   (	"ID_TIPO" NUMBER(*,0), 
	"TIPO" VARCHAR2(50 CHAR), 
	"DESCRIPCION" VARCHAR2(250 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FUNCIONALIDAD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FUNCIONALIDAD" 
   (	"CODIGO_FUNCIONALIDAD" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(200 CHAR), 
	"NOMBRE" VARCHAR2(100 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ROL" 
   (	"ID_ROL" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(25 BYTE), 
	"DESCRIPCION" VARCHAR2(250 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPO_CLIENTE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TIPO_CLIENTE" 
   (	"CODIGO_TIPO" NUMBER(*,0), 
	"TIPO" VARCHAR2(100 CHAR), 
	"DESCRIPCION" VARCHAR2(250 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPO_CUENTA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TIPO_CUENTA" 
   (	"CODIGO" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(200 CHAR), 
	"NOMBRE" VARCHAR2(100 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPO_TRANSACCION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TIPO_TRANSACCION" 
   (	"CODIGO_TIPO_TRANSAC" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 CHAR), 
	"DESCRIPCION" VARCHAR2(250 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRANSACCION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TRANSACCION" 
   (	"CORRELATIVO_TRANSACCION" NUMBER(*,0), 
	"FECHA" DATE, 
	"SALDO_INICIAL" FLOAT(126), 
	"SALDO_FINAL" FLOAT(126), 
	"VALOR" FLOAT(126), 
	"NO_AUTORIZACION" NUMBER(*,0), 
	"NO_RECHAZO" NUMBER(*,0), 
	"RAZON_RECHAZO" VARCHAR2(200 CHAR), 
	"EMPLEADO" NUMBER(*,0), 
	"AGENCIA" NUMBER(*,0), 
	"CUENTA" NUMBER(*,0), 
	"TIPO_TRANSACCION" NUMBER(*,0), 
	"EQUIPO" NUMBER(*,0), 
	"CHEQUE_EXTERNO" NUMBER(*,0), 
	"CHEQUE_LOCAL" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.AGENCIA
SET DEFINE OFF;
Insert into SYSTEM.AGENCIA (ID_AGENCIA,DIRECCION,DESCRIPCION) values (1,'Zona 1, Ciudad de Guatemala','banca central');
Insert into SYSTEM.AGENCIA (ID_AGENCIA,DIRECCION,DESCRIPCION) values (2,'zona 3, Quetzaltenango','sub banca');
Insert into SYSTEM.AGENCIA (ID_AGENCIA,DIRECCION,DESCRIPCION) values (3,'zona 5, jutiapa','sub banca');
REM INSERTING into SYSTEM.BANCO
SET DEFINE OFF;
REM INSERTING into SYSTEM.CHEQUE_EXTERNO
SET DEFINE OFF;
REM INSERTING into SYSTEM.CHEQUE_LOCAL
SET DEFINE OFF;
Insert into SYSTEM.CHEQUE_LOCAL (CODIGO_CHEQUE,FECHA,MONTO,CHEQUERA,ESTADO_CHEQUE) values (555,to_date('07/10/19','DD/MM/RR'),500,100,5);
Insert into SYSTEM.CHEQUE_LOCAL (CODIGO_CHEQUE,FECHA,MONTO,CHEQUERA,ESTADO_CHEQUE) values (120,to_date('10/08/19','DD/MM/RR'),400,100,5);
Insert into SYSTEM.CHEQUE_LOCAL (CODIGO_CHEQUE,FECHA,MONTO,CHEQUERA,ESTADO_CHEQUE) values (121,to_date('10/08/19','DD/MM/RR'),50,100,4);
REM INSERTING into SYSTEM.CHEQUERA
SET DEFINE OFF;
Insert into SYSTEM.CHEQUERA (CODIGO_CHEQUERA,CANTIDAD_CHEQUES,CUENTA,NUMERO_INICIO,NUMERO_FINAL,ESTADO_CHEQUERA) values (100,100,14,100,200,3);
REM INSERTING into SYSTEM.CLIENTE
SET DEFINE OFF;
Insert into SYSTEM.CLIENTE (CODIGO_CLIENTE,NOMBRE,DIRECCION,NIT,TELEFONO,CORREO,TIPO_CLIENTE,DPI) values (9,'sergio','7ma calle a',7044526,44454581,'a@b.com',1,'2162837790115');
REM INSERTING into SYSTEM.CLIENTE_CUENTA
SET DEFINE OFF;
Insert into SYSTEM.CLIENTE_CUENTA (CLIENTE,CUENTA) values (9,14);
REM INSERTING into SYSTEM.CUENTA
SET DEFINE OFF;
Insert into SYSTEM.CUENTA (NUMERO_CUENTA,ESTADO,SALDO_DISPONIBLE,ESTADO_CUENTA,EN_RESERVA,TIPO_CUENTA) values (14,'1',250,1,0,1);
Insert into SYSTEM.CUENTA (NUMERO_CUENTA,ESTADO,SALDO_DISPONIBLE,ESTADO_CUENTA,EN_RESERVA,TIPO_CUENTA) values (15,'1',150,1,0,1);
REM INSERTING into SYSTEM.EMPLEADO
SET DEFINE OFF;
Insert into SYSTEM.EMPLEADO (CODIGO_EMPLEADO,NOMBRE,DIRECCION,TELEFONO,CORREO,ROL,AGENCIA,DPI,CONTRASENA) values (1,'empleado1','casa',911,'@empleado',1,1,'2256','hola');
REM INSERTING into SYSTEM.EQUIPO
SET DEFINE OFF;
Insert into SYSTEM.EQUIPO (SKU,DESCRIPCION,AGENCIA_ID_AGENCIA) values (0,'principal',1);
REM INSERTING into SYSTEM.ESTADO_CHEQUE
SET DEFINE OFF;
Insert into SYSTEM.ESTADO_CHEQUE (CODIGO,DESCRIPCION,NOMBRE) values (1,null,'normal');
Insert into SYSTEM.ESTADO_CHEQUE (CODIGO,DESCRIPCION,NOMBRE) values (2,null,'extraviado');
Insert into SYSTEM.ESTADO_CHEQUE (CODIGO,DESCRIPCION,NOMBRE) values (3,null,'robado');
Insert into SYSTEM.ESTADO_CHEQUE (CODIGO,DESCRIPCION,NOMBRE) values (4,'cobrado','cobrado');
Insert into SYSTEM.ESTADO_CHEQUE (CODIGO,DESCRIPCION,NOMBRE) values (5,'rechazado','rechazado');
REM INSERTING into SYSTEM.ESTADO_CHEQUERA
SET DEFINE OFF;
Insert into SYSTEM.ESTADO_CHEQUERA (CODIGO_ESTADO,NOMBRE,DESCRIPCION) values (1,'Solicitada',null);
Insert into SYSTEM.ESTADO_CHEQUERA (CODIGO_ESTADO,NOMBRE,DESCRIPCION) values (2,'En Proceso',null);
Insert into SYSTEM.ESTADO_CHEQUERA (CODIGO_ESTADO,NOMBRE,DESCRIPCION) values (3,'Entregada',null);
REM INSERTING into SYSTEM.ESTADO_CUENTA
SET DEFINE OFF;
Insert into SYSTEM.ESTADO_CUENTA (CODIGO_ESTADO,NOMBRE,DESCRIPCION) values (3,'cancelada','Esta cancelada');
Insert into SYSTEM.ESTADO_CUENTA (CODIGO_ESTADO,NOMBRE,DESCRIPCION) values (2,'bloqueada','Tiene problema');
Insert into SYSTEM.ESTADO_CUENTA (CODIGO_ESTADO,NOMBRE,DESCRIPCION) values (1,'activa
','Estado normal');
REM INSERTING into SYSTEM.ESTADO_LOTE
SET DEFINE OFF;
REM INSERTING into SYSTEM.FUNCIONALIDAD
SET DEFINE OFF;
REM INSERTING into SYSTEM.ROL
SET DEFINE OFF;
Insert into SYSTEM.ROL (ID_ROL,NOMBRE,DESCRIPCION) values (1,'DBA',null);
Insert into SYSTEM.ROL (ID_ROL,NOMBRE,DESCRIPCION) values (2,'VISA',null);
Insert into SYSTEM.ROL (ID_ROL,NOMBRE,DESCRIPCION) values (3,'RECEPTOR',null);
REM INSERTING into SYSTEM.TIPO_CLIENTE
SET DEFINE OFF;
Insert into SYSTEM.TIPO_CLIENTE (CODIGO_TIPO,TIPO,DESCRIPCION) values (1,'normal','cliente normal');
REM INSERTING into SYSTEM.TIPO_CUENTA
SET DEFINE OFF;
Insert into SYSTEM.TIPO_CUENTA (CODIGO,DESCRIPCION,NOMBRE) values (1,'Personal','Personal');
Insert into SYSTEM.TIPO_CUENTA (CODIGO,DESCRIPCION,NOMBRE) values (2,'Mancomunada','Varias personas');
REM INSERTING into SYSTEM.TIPO_TRANSACCION
SET DEFINE OFF;
Insert into SYSTEM.TIPO_TRANSACCION (CODIGO_TIPO_TRANSAC,NOMBRE,DESCRIPCION) values (0,'debito',null);
Insert into SYSTEM.TIPO_TRANSACCION (CODIGO_TIPO_TRANSAC,NOMBRE,DESCRIPCION) values (1,'credito',null);
REM INSERTING into SYSTEM.TRANSACCION
SET DEFINE OFF;
Insert into SYSTEM.TRANSACCION (CORRELATIVO_TRANSACCION,FECHA,SALDO_INICIAL,SALDO_FINAL,VALOR,NO_AUTORIZACION,NO_RECHAZO,RAZON_RECHAZO,EMPLEADO,AGENCIA,CUENTA,TIPO_TRANSACCION,EQUIPO,CHEQUE_EXTERNO,CHEQUE_LOCAL) values (2,to_date('08/10/19','DD/MM/RR'),0,0,400,null,1,'NO TIENE FONDOS',1,1,14,0,0,null,120);
Insert into SYSTEM.TRANSACCION (CORRELATIVO_TRANSACCION,FECHA,SALDO_INICIAL,SALDO_FINAL,VALOR,NO_AUTORIZACION,NO_RECHAZO,RAZON_RECHAZO,EMPLEADO,AGENCIA,CUENTA,TIPO_TRANSACCION,EQUIPO,CHEQUE_EXTERNO,CHEQUE_LOCAL) values (3,to_date('08/10/19','DD/MM/RR'),0,0,50,null,null,null,1,1,14,0,0,null,121);
Insert into SYSTEM.TRANSACCION (CORRELATIVO_TRANSACCION,FECHA,SALDO_INICIAL,SALDO_FINAL,VALOR,NO_AUTORIZACION,NO_RECHAZO,RAZON_RECHAZO,EMPLEADO,AGENCIA,CUENTA,TIPO_TRANSACCION,EQUIPO,CHEQUE_EXTERNO,CHEQUE_LOCAL) values (4,to_date('08/10/19','DD/MM/RR'),0,0,50,null,null,null,1,1,14,0,0,null,null);
Insert into SYSTEM.TRANSACCION (CORRELATIVO_TRANSACCION,FECHA,SALDO_INICIAL,SALDO_FINAL,VALOR,NO_AUTORIZACION,NO_RECHAZO,RAZON_RECHAZO,EMPLEADO,AGENCIA,CUENTA,TIPO_TRANSACCION,EQUIPO,CHEQUE_EXTERNO,CHEQUE_LOCAL) values (5,to_date('08/10/19','DD/MM/RR'),0,0,50,null,null,null,1,1,15,1,0,null,null);
--------------------------------------------------------
--  DDL for Index AGENCIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."AGENCIA_PK" ON "SYSTEM"."AGENCIA" ("ID_AGENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BANCO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."BANCO_PK" ON "SYSTEM"."BANCO" ("ID_BANCO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHEQUE_LOCALV1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CHEQUE_LOCALV1_PK" ON "SYSTEM"."CHEQUE_EXTERNO" ("CODIGO_CHEQUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHEQUE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CHEQUE_PK" ON "SYSTEM"."CHEQUE_LOCAL" ("CODIGO_CHEQUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHEQUERA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CHEQUERA_PK" ON "SYSTEM"."CHEQUERA" ("CODIGO_CHEQUERA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CLIENTE_PK" ON "SYSTEM"."CLIENTE" ("CODIGO_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENTE_CUENTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CLIENTE_CUENTA_PK" ON "SYSTEM"."CLIENTE_CUENTA" ("CLIENTE", "CUENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CUENTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CUENTA_PK" ON "SYSTEM"."CUENTA" ("NUMERO_CUENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLEADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EMPLEADO_PK" ON "SYSTEM"."EMPLEADO" ("CODIGO_EMPLEADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TERMINAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TERMINAL_PK" ON "SYSTEM"."EQUIPO" ("SKU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPO_CHEQUE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TIPO_CHEQUE_PK" ON "SYSTEM"."ESTADO_CHEQUE" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ESTADO_CHEQUERA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ESTADO_CHEQUERA_PK" ON "SYSTEM"."ESTADO_CHEQUERA" ("CODIGO_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ESTADO_CUENTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ESTADO_CUENTA_PK" ON "SYSTEM"."ESTADO_CUENTA" ("CODIGO_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPO_LOTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TIPO_LOTE_PK" ON "SYSTEM"."ESTADO_LOTE" ("ID_TIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERMISO_PKV2
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PERMISO_PKV2" ON "SYSTEM"."FUNCIONALIDAD" ("CODIGO_FUNCIONALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ROL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ROL_PK" ON "SYSTEM"."ROL" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPO_CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TIPO_CLIENTE_PK" ON "SYSTEM"."TIPO_CLIENTE" ("CODIGO_TIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPO_CUENTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TIPO_CUENTA_PK" ON "SYSTEM"."TIPO_CUENTA" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPO_TRANSACCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TIPO_TRANSACCION_PK" ON "SYSTEM"."TIPO_TRANSACCION" ("CODIGO_TIPO_TRANSAC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TRANSACCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TRANSACCION_PK" ON "SYSTEM"."TRANSACCION" ("CORRELATIVO_TRANSACCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger AGENCIA_ID_AGENCIA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."AGENCIA_ID_AGENCIA_TRG" BEFORE
    INSERT ON agencia
    FOR EACH ROW
     WHEN ( new.id_agencia IS NULL ) BEGIN
    :new.id_agencia := agencia_id_agencia_seq.nextval;
END;

/
ALTER TRIGGER "SYSTEM"."AGENCIA_ID_AGENCIA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BANCO_ID_BANCO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."BANCO_ID_BANCO_TRG" BEFORE
    INSERT ON banco
    FOR EACH ROW
     WHEN ( new.id_banco IS NULL ) BEGIN
    :new.id_banco := banco_id_banco_seq.nextval;
END;

/
ALTER TRIGGER "SYSTEM"."BANCO_ID_BANCO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CHEQUE_EXTERNO_CODIGO_CHEQUE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."CHEQUE_EXTERNO_CODIGO_CHEQUE" BEFORE
    INSERT ON cheque_externo
    FOR EACH ROW
     WHEN ( new.codigo_cheque IS NULL ) BEGIN
    :new.codigo_cheque := cheque_externo_codigo_cheque.nextval;
END;

/
ALTER TRIGGER "SYSTEM"."CHEQUE_EXTERNO_CODIGO_CHEQUE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CHEQUE_LOCAL_CODIGO_CHEQUE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."CHEQUE_LOCAL_CODIGO_CHEQUE_TRG" BEFORE
    INSERT ON cheque_local
    FOR EACH ROW
     WHEN ( new.codigo_cheque IS NULL ) BEGIN
    :new.codigo_cheque := cheque_local_codigo_cheque_seq.nextval;
END;

/
ALTER TRIGGER "SYSTEM"."CHEQUE_LOCAL_CODIGO_CHEQUE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CHEQUERA_CODIGO_CHEQUERA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."CHEQUERA_CODIGO_CHEQUERA_TRG" BEFORE
    INSERT ON chequera
    FOR EACH ROW
     WHEN ( new.codigo_chequera IS NULL ) BEGIN
    :new.codigo_chequera := chequera_codigo_chequera_seq.nextval;
END;

/
ALTER TRIGGER "SYSTEM"."CHEQUERA_CODIGO_CHEQUERA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CHEQUERA_ID__TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."CHEQUERA_ID__TRG" BEFORE
    INSERT ON chequera
    FOR EACH ROW
     WHEN ( new.codigo_chequera IS NULL ) BEGIN
    :new.codigo_chequera := chequera_id_seq.nextval;
END;

/
ALTER TRIGGER "SYSTEM"."CHEQUERA_ID__TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CLIENTE_CODIGO_CLIENTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."CLIENTE_CODIGO_CLIENTE_TRG" BEFORE
    INSERT ON cliente
    FOR EACH ROW
     WHEN ( new.codigo_cliente IS NULL ) BEGIN
    :new.codigo_cliente := cliente_codigo_cliente_seq.nextval;
END;

/
ALTER TRIGGER "SYSTEM"."CLIENTE_CODIGO_CLIENTE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CUENTA_NUMERO_CUENTA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."CUENTA_NUMERO_CUENTA_TRG" BEFORE
    INSERT ON cuenta
    FOR EACH ROW
     WHEN ( new.numero_cuenta IS NULL ) BEGIN
    :new.numero_cuenta := cuenta_numero_cuenta_seq.nextval;
END;

/
ALTER TRIGGER "SYSTEM"."CUENTA_NUMERO_CUENTA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLEADO_CODIGO_EMPLEADO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."EMPLEADO_CODIGO_EMPLEADO_TRG" BEFORE
    INSERT ON empleado
    FOR EACH ROW
     WHEN ( new.codigo_empleado IS NULL ) BEGIN
    :new.codigo_empleado := empleado_codigo_empleado_seq.nextval;
END;

/
ALTER TRIGGER "SYSTEM"."EMPLEADO_CODIGO_EMPLEADO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EQUIPO_SKU_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."EQUIPO_SKU_TRG" BEFORE
    INSERT ON equipo
    FOR EACH ROW
     WHEN ( new.sku IS NULL ) BEGIN
    :new.sku := equipo_sku_seq.nextval;
END;

/
ALTER TRIGGER "SYSTEM"."EQUIPO_SKU_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ESTADO_CHEQUE_CODIGO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."ESTADO_CHEQUE_CODIGO_TRG" BEFORE
    INSERT ON estado_cheque
    FOR EACH ROW
     WHEN ( new.codigo IS NULL ) BEGIN
    :new.codigo := estado_cheque_codigo_seq.nextval;
END;

/
ALTER TRIGGER "SYSTEM"."ESTADO_CHEQUE_CODIGO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ESTADO_CHEQUERA_CODIGO_ESTADO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."ESTADO_CHEQUERA_CODIGO_ESTADO" BEFORE
    INSERT ON estado_chequera
    FOR EACH ROW
     WHEN ( new.codigo_estado IS NULL ) BEGIN
    :new.codigo_estado := estado_chequera_codigo_estado.nextval;
END;

/
ALTER TRIGGER "SYSTEM"."ESTADO_CHEQUERA_CODIGO_ESTADO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ESTADO_CUENTA_CODIGO_ESTADO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."ESTADO_CUENTA_CODIGO_ESTADO" BEFORE
    INSERT ON estado_cuenta
    FOR EACH ROW
     WHEN ( new.codigo_estado IS NULL ) BEGIN
    :new.codigo_estado := estado_cuenta_codigo_estado.nextval;
END;

/
ALTER TRIGGER "SYSTEM"."ESTADO_CUENTA_CODIGO_ESTADO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ESTADO_LOTE_ID_TIPO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."ESTADO_LOTE_ID_TIPO_TRG" BEFORE
    INSERT ON estado_lote
    FOR EACH ROW
     WHEN ( new.id_tipo IS NULL ) BEGIN
    :new.id_tipo := estado_lote_id_tipo_seq.nextval;
END;

/
ALTER TRIGGER "SYSTEM"."ESTADO_LOTE_ID_TIPO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FUNCIONALIDAD_CODIGO_FUNCIONAL
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."FUNCIONALIDAD_CODIGO_FUNCIONAL" BEFORE
    INSERT ON funcionalidad
    FOR EACH ROW
     WHEN ( new.codigo_funcionalidad IS NULL ) BEGIN
    :new.codigo_funcionalidad := funcionalidad_codigo_funcional.nextval;
END;

/
ALTER TRIGGER "SYSTEM"."FUNCIONALIDAD_CODIGO_FUNCIONAL" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ROL_ID_ROL_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."ROL_ID_ROL_TRG" BEFORE
    INSERT ON rol
    FOR EACH ROW
     WHEN ( new.id_rol IS NULL ) BEGIN
    :new.id_rol := rol_id_rol_seq.nextval;
END;

/
ALTER TRIGGER "SYSTEM"."ROL_ID_ROL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TIPO_CLIENTE_CODIGO_TIPO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."TIPO_CLIENTE_CODIGO_TIPO_TRG" BEFORE
    INSERT ON tipo_cliente
    FOR EACH ROW
     WHEN ( new.codigo_tipo IS NULL ) BEGIN
    :new.codigo_tipo := tipo_cliente_codigo_tipo_seq.nextval;
END;

/
ALTER TRIGGER "SYSTEM"."TIPO_CLIENTE_CODIGO_TIPO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRANSACCION_CORRELATIVO_TRANSA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."TRANSACCION_CORRELATIVO_TRANSA" BEFORE
    INSERT ON transaccion
    FOR EACH ROW
     WHEN ( new.correlativo_transaccion IS NULL ) BEGIN
    :new.correlativo_transaccion := transaccion_correlativo_transa.nextval;
END;

/
ALTER TRIGGER "SYSTEM"."TRANSACCION_CORRELATIVO_TRANSA" ENABLE;
--------------------------------------------------------
--  Constraints for Table AGENCIA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AGENCIA" ADD CONSTRAINT "AGENCIA_PK" PRIMARY KEY ("ID_AGENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."AGENCIA" MODIFY ("ID_AGENCIA" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."AGENCIA" MODIFY ("DIRECCION" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."AGENCIA" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BANCO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BANCO" ADD CONSTRAINT "BANCO_PK" PRIMARY KEY ("ID_BANCO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."BANCO" MODIFY ("ID_BANCO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."BANCO" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHEQUE_EXTERNO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CHEQUE_EXTERNO" ADD CONSTRAINT "CHEQUE_LOCALV1_PK" PRIMARY KEY ("CODIGO_CHEQUE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."CHEQUE_EXTERNO" MODIFY ("CODIGO_CHEQUE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CHEQUE_EXTERNO" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CHEQUE_EXTERNO" MODIFY ("MONTO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CHEQUE_EXTERNO" MODIFY ("BANCO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CHEQUE_EXTERNO" MODIFY ("LOTE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CHEQUE_EXTERNO" MODIFY ("ESTADO_CHEQUE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHEQUE_LOCAL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CHEQUE_LOCAL" ADD CONSTRAINT "CHEQUE_PK" PRIMARY KEY ("CODIGO_CHEQUE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."CHEQUE_LOCAL" MODIFY ("CODIGO_CHEQUE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CHEQUE_LOCAL" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CHEQUE_LOCAL" MODIFY ("MONTO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CHEQUE_LOCAL" MODIFY ("CHEQUERA" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CHEQUE_LOCAL" MODIFY ("ESTADO_CHEQUE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHEQUERA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CHEQUERA" ADD CONSTRAINT "CHEQUERA_PK" PRIMARY KEY ("CODIGO_CHEQUERA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."CHEQUERA" MODIFY ("CODIGO_CHEQUERA" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CHEQUERA" MODIFY ("CANTIDAD_CHEQUES" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CHEQUERA" MODIFY ("CUENTA" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CHEQUERA" MODIFY ("ESTADO_CHEQUERA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("CODIGO_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."CLIENTE" MODIFY ("CODIGO_CLIENTE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENTE" MODIFY ("DIRECCION" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENTE" MODIFY ("NIT" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENTE" MODIFY ("TELEFONO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENTE" MODIFY ("CORREO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENTE" MODIFY ("TIPO_CLIENTE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENTE" MODIFY ("FOTO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENTE" MODIFY ("FIRMA" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENTE" MODIFY ("DPI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTE_CUENTA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CLIENTE_CUENTA" ADD CONSTRAINT "CLIENTE_CUENTA_PK" PRIMARY KEY ("CLIENTE", "CUENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."CLIENTE_CUENTA" MODIFY ("CLIENTE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENTE_CUENTA" MODIFY ("CUENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUENTA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CUENTA" ADD CONSTRAINT "CUENTA_PK" PRIMARY KEY ("NUMERO_CUENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."CUENTA" MODIFY ("ESTADO" CONSTRAINT "NNC_CUENTA_ESTADO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CUENTA" MODIFY ("ESTADO_CUENTA" CONSTRAINT "NNC_CUENTA_ESTADO_CUENTA" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CUENTA" MODIFY ("NUMERO_CUENTA" CONSTRAINT "NNC_CUENTA_ID_CUENTA" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CUENTA" MODIFY ("SALDO_DISPONIBLE" CONSTRAINT "NNC_CUENTA_SALDO_DISPONIBLE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CUENTA" MODIFY ("TIPO_CUENTA" CONSTRAINT "NNC_CUENTA_TIPO_CUENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLEADO" ADD CONSTRAINT "EMPLEADO_PK" PRIMARY KEY ("CODIGO_EMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."EMPLEADO" MODIFY ("CODIGO_EMPLEADO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLEADO" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLEADO" MODIFY ("DIRECCION" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLEADO" MODIFY ("TELEFONO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLEADO" MODIFY ("CORREO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLEADO" MODIFY ("ROL" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLEADO" MODIFY ("AGENCIA" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLEADO" MODIFY ("DPI" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLEADO" MODIFY ("CONTRASENA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EQUIPO" MODIFY ("SKU" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EQUIPO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EQUIPO" MODIFY ("AGENCIA_ID_AGENCIA" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EQUIPO" ADD CONSTRAINT "TERMINAL_PK" PRIMARY KEY ("SKU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTADO_CHEQUE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ESTADO_CHEQUE" MODIFY ("CODIGO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ESTADO_CHEQUE" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ESTADO_CHEQUE" ADD CONSTRAINT "TIPO_CHEQUE_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTADO_CHEQUERA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ESTADO_CHEQUERA" ADD CONSTRAINT "ESTADO_CHEQUERA_PK" PRIMARY KEY ("CODIGO_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."ESTADO_CHEQUERA" MODIFY ("CODIGO_ESTADO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ESTADO_CHEQUERA" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADO_CUENTA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ESTADO_CUENTA" ADD CONSTRAINT "ESTADO_CUENTA_PK" PRIMARY KEY ("CODIGO_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."ESTADO_CUENTA" MODIFY ("CODIGO_ESTADO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ESTADO_CUENTA" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADO_LOTE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ESTADO_LOTE" MODIFY ("ID_TIPO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ESTADO_LOTE" MODIFY ("TIPO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ESTADO_LOTE" ADD CONSTRAINT "TIPO_LOTE_PK" PRIMARY KEY ("ID_TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FUNCIONALIDAD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FUNCIONALIDAD" ADD CONSTRAINT "PERMISO_PKV2" PRIMARY KEY ("CODIGO_FUNCIONALIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."FUNCIONALIDAD" MODIFY ("CODIGO_FUNCIONALIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ROL" ADD CONSTRAINT "ROL_PK" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_CLIENTE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TIPO_CLIENTE" MODIFY ("CODIGO_TIPO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TIPO_CLIENTE" ADD CONSTRAINT "TIPO_CLIENTE_PK" PRIMARY KEY ("CODIGO_TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_CUENTA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TIPO_CUENTA" MODIFY ("CODIGO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TIPO_CUENTA" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TIPO_CUENTA" ADD CONSTRAINT "TIPO_CUENTA_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_TRANSACCION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TIPO_TRANSACCION" MODIFY ("CODIGO_TIPO_TRANSAC" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TIPO_TRANSACCION" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TIPO_TRANSACCION" ADD CONSTRAINT "TIPO_TRANSACCION_PK" PRIMARY KEY ("CODIGO_TIPO_TRANSAC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSACCION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TRANSACCION" MODIFY ("CORRELATIVO_TRANSACCION" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TRANSACCION" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TRANSACCION" MODIFY ("SALDO_INICIAL" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TRANSACCION" MODIFY ("SALDO_FINAL" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TRANSACCION" MODIFY ("VALOR" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TRANSACCION" MODIFY ("EMPLEADO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TRANSACCION" MODIFY ("AGENCIA" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TRANSACCION" MODIFY ("CUENTA" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TRANSACCION" MODIFY ("TIPO_TRANSACCION" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TRANSACCION" MODIFY ("EQUIPO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TRANSACCION" ADD CONSTRAINT "TRANSACCION_PK" PRIMARY KEY ("CORRELATIVO_TRANSACCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHEQUE_EXTERNO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CHEQUE_EXTERNO" ADD CONSTRAINT "BANCO_FK" FOREIGN KEY ("BANCO")
	  REFERENCES "SYSTEM"."BANCO" ("ID_BANCO") ENABLE;
 
  ALTER TABLE "SYSTEM"."CHEQUE_EXTERNO" ADD CONSTRAINT "ESTADO_CHEQUE_FK" FOREIGN KEY ("ESTADO_CHEQUE")
	  REFERENCES "SYSTEM"."ESTADO_CHEQUE" ("CODIGO") ENABLE;
 
  ALTER TABLE "SYSTEM"."CHEQUE_EXTERNO" ADD CONSTRAINT "LOTE_FK" FOREIGN KEY ("LOTE")
	  REFERENCES "SYSTEM"."LOTE" ("ID_LOTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHEQUE_LOCAL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CHEQUE_LOCAL" ADD CONSTRAINT "CHEQUERA_FK" FOREIGN KEY ("CHEQUERA")
	  REFERENCES "SYSTEM"."CHEQUERA" ("CODIGO_CHEQUERA") ENABLE;
 
  ALTER TABLE "SYSTEM"."CHEQUE_LOCAL" ADD CONSTRAINT "ESTADO_CHEQUE_FKV2" FOREIGN KEY ("ESTADO_CHEQUE")
	  REFERENCES "SYSTEM"."ESTADO_CHEQUE" ("CODIGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHEQUERA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CHEQUERA" ADD CONSTRAINT "CHEQUERA_CUENTA_FK" FOREIGN KEY ("CUENTA")
	  REFERENCES "SYSTEM"."CUENTA" ("NUMERO_CUENTA") ENABLE;
 
  ALTER TABLE "SYSTEM"."CHEQUERA" ADD CONSTRAINT "ESTADO_CHEQUERA" FOREIGN KEY ("ESTADO_CHEQUERA")
	  REFERENCES "SYSTEM"."ESTADO_CHEQUERA" ("CODIGO_ESTADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CLIENTE" ADD CONSTRAINT "CLIENTE_TIPO_CLIENTE_FK" FOREIGN KEY ("TIPO_CLIENTE")
	  REFERENCES "SYSTEM"."TIPO_CLIENTE" ("CODIGO_TIPO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTE_CUENTA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CLIENTE_CUENTA" ADD CONSTRAINT "CLIENTE_CUENTA_CLIENTE_FK" FOREIGN KEY ("CLIENTE")
	  REFERENCES "SYSTEM"."CLIENTE" ("CODIGO_CLIENTE") ENABLE;
 
  ALTER TABLE "SYSTEM"."CLIENTE_CUENTA" ADD CONSTRAINT "CLIENTE_CUENTA_CUENTA_FK" FOREIGN KEY ("CUENTA")
	  REFERENCES "SYSTEM"."CUENTA" ("NUMERO_CUENTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUENTA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CUENTA" ADD CONSTRAINT "CUENTA_ESTADO_CUENTA_FK" FOREIGN KEY ("ESTADO_CUENTA")
	  REFERENCES "SYSTEM"."ESTADO_CUENTA" ("CODIGO_ESTADO") ENABLE;
 
  ALTER TABLE "SYSTEM"."CUENTA" ADD CONSTRAINT "CUENTA_TIPO_CUENTA_FK" FOREIGN KEY ("TIPO_CUENTA")
	  REFERENCES "SYSTEM"."TIPO_CUENTA" ("CODIGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLEADO" ADD CONSTRAINT "AGENCIA" FOREIGN KEY ("AGENCIA")
	  REFERENCES "SYSTEM"."AGENCIA" ("ID_AGENCIA") ENABLE;
 
  ALTER TABLE "SYSTEM"."EMPLEADO" ADD CONSTRAINT "ROL" FOREIGN KEY ("ROL")
	  REFERENCES "SYSTEM"."ROL" ("ID_ROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EQUIPO" ADD CONSTRAINT "EQUIPO_AGENCIA_FK" FOREIGN KEY ("AGENCIA_ID_AGENCIA")
	  REFERENCES "SYSTEM"."AGENCIA" ("ID_AGENCIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACCION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TRANSACCION" ADD CONSTRAINT "AGENCIA_FK" FOREIGN KEY ("AGENCIA")
	  REFERENCES "SYSTEM"."AGENCIA" ("ID_AGENCIA") ENABLE;
 
  ALTER TABLE "SYSTEM"."TRANSACCION" ADD CONSTRAINT "CHEQUE_EXTERNO" FOREIGN KEY ("CHEQUE_EXTERNO")
	  REFERENCES "SYSTEM"."CHEQUE_EXTERNO" ("CODIGO_CHEQUE") ENABLE;
 
  ALTER TABLE "SYSTEM"."TRANSACCION" ADD CONSTRAINT "CHEQUE_LOCAL" FOREIGN KEY ("CHEQUE_LOCAL")
	  REFERENCES "SYSTEM"."CHEQUE_LOCAL" ("CODIGO_CHEQUE") ENABLE;
 
  ALTER TABLE "SYSTEM"."TRANSACCION" ADD CONSTRAINT "CUENTA_FK" FOREIGN KEY ("CUENTA")
	  REFERENCES "SYSTEM"."CUENTA" ("NUMERO_CUENTA") ENABLE;
 
  ALTER TABLE "SYSTEM"."TRANSACCION" ADD CONSTRAINT "EMPLEADO_FK" FOREIGN KEY ("EMPLEADO")
	  REFERENCES "SYSTEM"."EMPLEADO" ("CODIGO_EMPLEADO") ENABLE;
 
  ALTER TABLE "SYSTEM"."TRANSACCION" ADD CONSTRAINT "EQUIPO_FK" FOREIGN KEY ("EQUIPO")
	  REFERENCES "SYSTEM"."EQUIPO" ("SKU") ENABLE;
 
  ALTER TABLE "SYSTEM"."TRANSACCION" ADD CONSTRAINT "TIPO_TRANSACCION_FK" FOREIGN KEY ("TIPO_TRANSACCION")
	  REFERENCES "SYSTEM"."TIPO_TRANSACCION" ("CODIGO_TIPO_TRANSAC") ENABLE;
